# Generated by Django 5.1.4 on 2025-03-24 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='contact',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
