# Generated by Django 5.1.4 on 2025-04-01 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0002_hotels_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='contact',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Контактный номер'),
        ),
    ]
