# Generated by Django 5.1.4 on 2025-03-12 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0058_alter_favorite_unique_together_alter_favorite_hotels'),
    ]

    operations = [
        migrations.AddField(
            model_name='replytoattractionreview',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='replytohotelreview',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='replytokitchenreview',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='replytopopularreview',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
