# Generated by Django 5.1.4 on 2025-03-13 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0059_replytoattractionreview_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='airlinetickets',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='airline_logos/'),
        ),
    ]
